### ISSUE TITLE
Input matrix - raw or normalized?

### ISSUE THREAD

**Issue by CodeInTheSkies** [MSingerLab/COMETSC#2]
Hello there!  Thanks for your tool, and I'm excited to try it out!

I took a look at your preprint as well as the manual, but I'm still confused as to whether the raw or normalized data is better as the input matrix.  Both are accepted, I know.  But my question is, is any one input type more preferred (normalized, log-normalized, or raw)?

I have 10X data, processed by Seurat.  So, can I give as input to COMET the log-normalized data as pre-processed by Seurat v2?

Any advice would be very helpful!

Thanks!

**Comment by Cnrdelaney** [comment]
Hello! Thanks for reaching out.

I would say that, in general, the best input would depend on the context of your data. It is indeed true that the tool does not have a preference between the two so the extent to which a run is successful can be determined by the output. If the output with the normalized data does not have strict enough genes for example, count data can be used. To directly answer your question, you can absolutely give the log-normalized data as pre-processed by Seurat as long as the formatting fits the guidelines in the documentation! 

Let us know if you run into any troubles.
