### ISSUE TITLE
Explanation of output

### ISSUE THREAD

**Issue by CodeInTheSkies** [MSingerLab/COMETSC#3]
Hello there!

I am happy to say that this tool has been very useful to extract markers for our 10X data!

However, it would help us better to interpret the results if we are able to get more detailed explanations for each of the columns of a typical output table.

I would like to understand the meaning and interpretation of these columns:

HG_pval
TP
TN
q_value
HG_rank
CCS
MGD
CCS_rank
rank
Plot

Would be immensely helpful!

Many thanks :)

**Comment by Cnrdelaney** [comment]
Hello! Very happy to hear our tool has been useful. The columns are described as follows:

HG_pval - HyperGeometric p-value obtained from the hypergeometric test, this corresponds to statistical signifcance of the gene panel.
TP - True positive value, or the percentage of expressing cells in the cluster (using the given expression threshold).
TN - True negative value, or the percentage of non-expressing cells outside of the cluster (using the given expression threshold).
q_value - Q-value is an adjusted p-value
HG_rank - Ranking for the gene panel by lowest HG_pval
CCS - Cluster Clear Score, this is a value that assesses how much the additional gene (2- gene panels only) improves your True Negative score in other clusters. More about this can be read at our paper available on the bioarxiv (https://www.biorxiv.org/content/10.1101/655753v1)
MGD - Another way of scoring TN changes, not actually used at the moment
CCS_rank - Ranking of gene panel by highest CCS value
rank - Final rank of the panel, an aggregate of the HG_rank and the CCS_rank
Plot - 1 if the panel is plotted in the visualization files, 0 if it is not

In addition to this, there is some further description of the outputs on the documentation here (https://hgmd.readthedocs.io/en/latest/details.html#export-statistical-results)

Thanks and let me know if there is anything else confusing!
